### ISSUE TITLE
Heroes API Addition

### ISSUE THREAD

**Issue by Kainzo** [TechzoneMC/SpawnShield#14]
I'd like to have SpawnShield support Heroes combat.

When players take damage/go into combat they enter a combat state, this can be monitored to use for SpawnShield.

http://hc.to/javadocs
maven repo > http://nexus.theyeticave.net/content/repositories/pub_releases/

Thanks!

**Comment by Techcable** [comment]
Fixed in 95588b2e053818b0f6315d7089ff3fe14a774a44
