### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ghost** [TechzoneMC/SpawnShield#3]
The plugin isn't preventing players from going into blocked regions when they are in combat

**Comment by Techcable** [comment]
Are you on the latest version from the Jenkins?

**Comment by ghost** [comment]
IDK I am using the latest version from spigot

**Comment by Techcable** [comment]
Please try the latest version from [the jenkins](http://ci.techcable.net/job/SpawnShield/).

**Comment by ghost** [comment]
Didn't fix it it says to them they can't go into safe zones during pvp but doesn't stop them

**Comment by Techcable** [comment]
@timothydavidhart 
What forcefield mode are you on?

**Comment by ghost** [comment]
I want to use the third (glass one) but ive also tried the other two

**Comment by ghost** [comment]
Could it be because I'm using java 8

**Comment by Techcable** [comment]
What is your server logs and configs from the latest version?

**Comment by ghost** [comment]
The configs are on default here is my logs https://www.dropbox.com/s/x3xxvvjuf3g5xfd/latest.log?dl=1

**Comment by ghost** [comment]
Hello?

**Comment by Techcable** [comment]
@timothydavidhart 
Please try forcefield mode on the latest version.

**Comment by ghost** [comment]
I am on the latest version ive been on it for a while

**Comment by Techcable** [comment]
@timothydavidhart 
Are you using the forcefield mode?

**Comment by ghost** [comment]
I can't set it to forcefield mode It keeps changing back to teleport

**Comment by ghost** [comment]
Hello?

**Comment by Techcable** [comment]
I'l try and fix the config serialization.

**Comment by Techcable** [comment]
Try build 17.

**Comment by ghost** [comment]
it doesn't even try to keep you out now

**Comment by Techcable** [comment]
Build 18 works for me :)

**Comment by ghost** [comment]
Build 18 doesn't work atal the config file won't generate and the command is broken

**Comment by Techcable** [comment]
Logs on build #18 please.

**Comment by ghost** [comment]
http://www.forbiddencore.com/latest.log

**Comment by Techcable** [comment]
I don't think your config is valid.
Could you please delete it and reconfigure it.

**Comment by ghost** [comment]
There is no config in my server directory ive looked everywhere for it

**Comment by Techcable** [comment]
Have you checked the spawnshield directory in your plugin's folder?

**Comment by ghost** [comment]
No because it's not there

**Comment by ghost** [comment]
Hello?

**Comment by Techcable** [comment]
Update to build 19 please.

**Comment by ghost** [comment]
There is still no config and the plugin is still a little messed up

**Comment by Techcable** [comment]
@timothydavidhart 
Logs?

**Comment by ghost** [comment]
I will get you the logs as soon as I get home sit tight :)

**Comment by ghost** [comment]
I'm sorry to say this but my host is having internet problems right now and I have no idea when it will be fixed

**Comment by ghost** [comment]
Here is the log file www.forbiddencore.com/latest.log

**Comment by Techcable** [comment]
what files are in the spawnshield directory, and what are the values of it?
ARe you on the latest build?

**Comment by ghost** [comment]
I still don't have one

**Comment by Techcable** [comment]
What build are you on?

**Comment by ghost** [comment]
Latest

**Comment by Techcable** [comment]
Can you re-download [from the ci](http://ci.techcable.net/job/SpawnShield/)?
I'm pretty sure i fixed these problems.

**Comment by ghost** [comment]
That link doesn't work

**Comment by Techcable** [comment]
@timothydavidhart 
I just fixed it.

**Comment by ghost** [comment]
Still isn't there

**Comment by ghost** [comment]
The config file*

**Comment by ghost** [comment]
Hello?

**Comment by Techcable** [comment]
@timothydavidhart 
Try build 20.

**Comment by ghost** [comment]
I can't find build 20 on the Jenkins can you confirm it's there?

**Comment by Techcable** [comment]
@timothydavidhart 
I just told it to build, so it should be there in a few minutes.

**Comment by ghost** [comment]
Ok so build 20 fixes the plugin almost completely but there is one thing still being broken when I change the force field range from say 50 to 5 it keeps changing back to 50 thats all I have found

**Comment by Techcable** [comment]
@timothydavidhart 
Wow that is interesting.
Also, why are you using force field mode 5?

**Comment by ghost** [comment]
Well im finding it's causing alot of lag if you want I can send you a timmings report

**Comment by Techcable** [comment]
What are your machine's specs, and what are you running on it?
It should not cause any lag since it caches and updates are performed in another thread.
A timings report might help too.

**Comment by ghost** [comment]
CPU: Intel(R) Xeon(R) CPU L5520 @ 2.27GHz
Ram: 4 gigs of ddr3
Blazing fast SSD's

ram and cpu never go above 10%

Timings: http://timings.aikar.co/?url=11988728

**Comment by Techcable** [comment]
@timothydavidhart 
MCMMO is probably the cause of your lag.
Please open a new issue for the performance if you still have problems.

**Comment by ghost** [comment]
There is no lag for the server when your plugin is out I don't think it's that im sure if I can put it to 5 it will be fine

**Comment by Techcable** [comment]
@timothydavidhart 
Use [this script](https://gist.github.com/Techcable/4243b8f57b5715f417ee/) on your server, open the results in a webpage, save the webpage and give it to me.
It will run a profiler to find the source of the lag, which is **way** more acurate then timings.

**Comment by ghost** [comment]
How do I use the script?

**Comment by Techcable** [comment]
@timothydavidhart 
First of all open a new issue for the lag.
Its a shell script.
Run it using "bash profile.sh"
