### ISSUE TITLE
Plugin doesn't work correctly.

### ISSUE THREAD

**Issue by Aireesan** [TechzoneMC/SpawnShield#6]
http://prntscr.com/7x2pp5 that is my issue, the plugin does its job when it shouldn't. Mode is knockback.
Plugins:  GroupManager, HCFBan, NoPinger, AsyncWorldEditInjector, WorldEdit, MaxBans, Vault, PluginManagerReloaded, ConsoleSay, WorldGuard, PvPTimer, SilkSpawners, SpawnShield, DisableCommands, CoreProtect, ChestCommands, BiomeControl, ScheduledAnnouncer2, DeathMessages, Essentials, AsyncWorldEdit, ChatProtectionPlus, ServerSigns, EssentialsSpawn, TitleManager, EssentialsChat, AsyncWorldEdit-TitleManager, Factions, CombatTagPlus

**Comment by Techcable** [comment]
Logs?'
Are you sure you are using worldguard for regions, it looks like you are using factions.

**Comment by Aireesan** [comment]
Yeah, i'm using WG. Theres no log change, everything loads correctly, no errors.

**Comment by Techcable** [comment]
What do the logs say anways?

**Comment by Aireesan** [comment]
http://pasteninja.pw/Yv8eyCSNc

**Comment by Techcable** [comment]
Your log doesn't even think the server is loading SpawnShield.
Also, [Build 20](http://ci.techcable.net/job/SpawnShield/20/) should have some fixes.

**Comment by Techcable** [comment]
[Build 31](http://ci.techcable.net/job/SpawnShield/31/) is a confirmed fix
