### ISSUE TITLE
[glitch] Mounted players are ignored.

### ISSUE THREAD

**Issue by Ordrox** [TechzoneMC/SpawnShield#7]
Hey! Very nice plugin and works pretty well, anyway... SpawnShield seems to totaly ignore the players that are mounting a horse. They are receving many times the message (you can't enter...) in the safezone but no more.

With the Knockback effect, if they leave the mount while in combat in a safezone, they'll be slapped many times to the exit (still funny to see ^_^)

**Comment by Techcable** [comment]
This is a problem where I can't teleport mounted players.
Let me try and fix.

**Comment by Techcable** [comment]
[Build 28](ci.techcable.net/job/SpawnShield/28/) has compatibility with mounted players on versions bellow the latest 1.7.10. It also teleports whatever the player is mounted on.

**Comment by Ordrox** [comment]
Hum, i'm sorry to say i can't test the latest build. Since your last release (1.1.1) Spawnshield does not work anymore, players in combat entering a safezone create a lot of errors in the logs (http://pastebin.com/yGpaQrMV). If needed i can create a new issue.

**Comment by Techcable** [comment]
Yeah, please open a new issue.
State:
- What CombatTagging plugin you use
- What protection plugin you use
- What version of spawnshield you use
- What version of minecraft you use
