### ISSUE TITLE
Spawnshield doesn't work past 1.1.0

### ISSUE THREAD

**Issue by Ordrox** [TechzoneMC/SpawnShield#8]
Hi! the latest builds don't work anymore, the last version working for me is 1.1.0.

People tagged are abble to enter protected area, but the plugin spam an error in the logs: http://pastebin.com/1zfQW0h0

CombatTagging plugin: PvPmanager V3b149
Protection plugins: Factions v2.8, worldguard v6.1
Spawnshield: build 29
Server: Spigot 1.8.8

PS: We talked about it 3 days ago, i'm sooo late, sorry.

**Comment by Techcable** [comment]
[Build 31](http://ci.techcable.net/job/SpawnShield/31/) is a confirmed fix
