### ISSUE TITLE
How can we implement a plugin to replace combat tag ?

### ISSUE THREAD

**Issue by vmarchaud** [TechzoneMC/SpawnShield#9]
I just cant figured out how can i implement a new plugin to replace combat tag, i saw the interface, but just where i put my implementation ? I cant build it my self cause your maven repo is down.

Please explain how to do this and up your maven repo :)

**Comment by Techcable** [comment]
In a new maven module.

**Comment by vmarchaud** [comment]
Yeah but i cant compile it since your repo is down

**Comment by Techcable** [comment]
My repo is back up.
What plugin do you need supported?

**Comment by vmarchaud** [comment]
Sorry i dont need it anymore :x 
(and actually i dont really remember which one i needed ^^)
